### ISSUE TITLE
Please provide instructions how to run miew

### ISSUE THREAD

**Issue by yurivict** [epam/miew#119]
You say ```use it in your Webpack / Browserify / Rollup setup```. I installed ```Browserify```, now what do I do? Please provide detailed instructions on how to run it in each of the setups that you recommend.

I think that you assume that users are very knowledgeable in NodeJS technologies including all the latest developments in NodeJS. It is very optimistic to assume this.

**Comment by paulsmirnov** [comment]
Currently I see a couple of ways one could use the miew project.

💊 **As an end-user (e.g. scientist)** one would run the miew demo application, load and examine molecules, make screenshots etc. In this case the user accesses the [miew web site](http://miew.opensource.epam.com/) and interacts with it without any knowledge of the development tools.

🛠 **As a front-end developer** one would embed the miew library as a component into its own web application (or just a web page). In this case the user is assumed to have at least one of the front-end development skills:
- adding third-party scripts to his web pages,
- building own web application using third-party node.js packages (with [recently preferred webpack or the legacy browserify](https://www.npmtrends.com/browserify-vs-webpack)).

There are a few more cases of course (e.g. [contributing to the project](https://github.com/epam/miew/blob/latest/CONTRIBUTING.md)) but the main two are listed above. Which one is yours?

Pleas note that **you don't need to know node.js, webpack or browserify** even for the second case. Just follow the good old practice:
- download the minified [library](https://github.com/epam/miew/raw/latest/dist/Miew.min.js) and [styles](https://github.com/epam/miew/blob/latest/dist/Miew.min.css),
- read the [docs](https://github.com/epam/miew/blob/latest/docs/tutorials/embed.md) and follow the [example](https://github.com/epam/miew/blob/latest/examples/miew_via_global.html) to add a `<script>` tag and a `<div>` to you web page.

Check a [working demo](http://miew.opensource.epam.com/examples/miew_via_global.html) of this basic example or try the more [complex one](http://miew.opensource.epam.com/examples/grid.html).

Nevertheless, I admit there are still lots of docs we should write and provide with the library. The project is in development and is open-source one so everybody are welcome to contribute! 😃

**Comment by paulsmirnov** [comment]
@yurivict Do you need further assistance or the links above are enough?

**Comment by yurivict** [comment]
Thank you for your explanation!
