### ISSUE TITLE
Clearing memory from previously loaded proteins

### ISSUE THREAD

**Issue by IvanFon** [epam/miew#254]
Hi, I'm having some trouble clearing out the memory used by a previously loaded protein. The issue can be shown on [miew.app](https://miew.app/), with Firefox's memory profiler.

After loading the page, and without changing any settings, it's using 60 Mb of memory. After loading a large protein (I used `cif:5GJR`), it's now using 580 Mb. Now, if I load a small protein (I used `4CRM`), the page is using up 630 Mb.

It seems like, instead of clearing the memory when unloading a previous protein, it's stacking the memory. If I load and unload multiple proteins, the memory keeps growing.

I've been able to reproduce this on the latest Firefox and Chrome. I've tried `viewer.unload`, `viewer.halt`, and `viewer.term`, as well as initializing an entirely new viewer, but it seems like none of these methods clear old proteins from memory.

Please let me know if I'm doing something wrong, and thanks for the amazing library!

**Comment by NataliaDSmirnova** [comment]
Hi! Thank you for the report. I worry about the symptoms you've described  :worried:
Shortly this is not the behavior we've planned. I ask for a few days to investigate the problem.

**Comment by Hadegda** [comment]
Hi Ivan!
We reproduce you issue and we are interested in having more information)
Can I ask you to write more details? What instruments you used for profiling? How have you done profiling?

**Comment by Hadegda** [comment]
@IvanFon also one more question appeared
We reproduced this issue in Firefox.
However in Chrome we have another situation: on some molecules loading sequences we see such problem but not in case CIF:5GJR then 4CRM (see screenshot)
Did you have this issue in chrome on 5GJR, 4CRM sequence? What tools did you use for profiling in chrome?
![image](https://user-images.githubusercontent.com/14240731/73545435-64f1e880-444c-11ea-8e27-2122327e8ca4.png)

**Comment by Hadegda** [comment]
@IvanFon,
We found the reason, causes this problem. In some cases, molecules really did not unload from memory.
It is not exactly Miew problem. It goes from three.js. This is the link on the correspondent issue: https://github.com/mrdoob/three.js/pull/18411
We checked that their fix works for us. Hope they will approve this PR in nearest time :)

**Comment by IvanFon** [comment]
Thank you, that fix is working!
