### ISSUE TITLE
When loading some CIF files: TypeError: this.molecules[n] is undefined (CIFParser.js)

### ISSUE THREAD

**Issue by IvanFon** [epam/miew#270]
**Describe the bug**
When loading some CIF files, the parser throws an error, and the protein isn't loaded.

**To Reproduce**
1. Go to [miew.app](https://miew.app/)
2. Load `cif:6rfr` or `cif:6gcs`
3. Miew throws parsing error

Can also reproduce when directly downloading CIF files from PDB and uploading them into Miew.

**Expected behavior**
Protein is parsed and loaded correctly.

**Desktop (please complete the following information):**
 - OS: Arch Linux (5.5.9-arch1-2)
 - Browser: Firefox 75.0b3 (64-bit), Chromium 80.0.3987.132 (Official Build) Arch Linux (64-bit)

**Additional context**
Firefox console error:

`TypeError: this.molecules[n] is undefined CIFParser.js:221:6`

Chrome console error:
```
Uncaught (in promise) TypeError: Cannot set property 'name' of undefined
    at t.value (CIFParser.js:221)
    at t.value (CIFParser.js:178)
    at t.value (CIFParser.js:163)
    at Parser.js:21
```
![chrome-error](https://user-images.githubusercontent.com/1174413/77125195-ff2de000-6a3c-11ea-9b84-cea9510bcf69.png)

**Comment by NataliaDSmirnova** [comment]
Thanks for the report. We need some time to investigate the problem.

**Comment by NataliaDSmirnova** [comment]
@IvanFon, we've found place of the bug. Your protein has an unforeseen molucule organization. That's my mistake 😞  For the fast fix I want to offer the changes https://github.com/epam/miew/commit/dda4047e74656f2695d7bc997cfd9637d9879651. 
I need a couple of days to test the solution and aprove it.

**Comment by IvanFon** [comment]
Thank you for the quick fix! It seems to be working :)

**Comment by NataliaDSmirnova** [comment]
We've done https://github.com/epam/miew/commit/6f8d7a0a29d1e9bc4a7344774b5546c06ec614f6.
Please, check the solution: https://miew.app/master/?l=cif:6GCS

**Comment by IvanFon** [comment]
Sorry, forgot to leave a comment, looks like it's fixed. Thank you!
