### ISSUE TITLE
How to properly dispose of view?

### ISSUE THREAD

**Issue by agavram** [epam/miew#297]
Running version v0.9.0. 

According to the [`miew_via_react` ](https://github.com/epam/miew/blob/8cd92e1bdc30221eb5d87590c7a9b34cabbab743/packages/lib/examples/miew_via_react/components/ViewerContainer.js#L32)example calling .dispose() should properly clean up the view. However attempting to call the same function in an angular project I am met with: `this.view.dispose is not a function`.

Everything else works flawlessly, but performance on the site is hampered if I cannot remove the view.

**Comment by agavram** [comment]
Turns out using .halt() works

**Comment by NataliaDSmirnova** [comment]
Great, you've found the solution 👍
