### ISSUE TITLE
S-Group displaying in 3D view

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/miew#304]
As a Ketcher User I want to see S-Groups brackets in 3D view. So that I can understand which part of structure is complex.
Now there are no brackets in Miew viewer.

**Comment by paulsmirnov** [comment]
@KseniiaSemenishcheva You are right, 2D graphics in Ketcher's 3D viewer is limited. As far as I remember, Ketcher used an older version of Miew embedded directly in its sources. So, any changes to the viewer will not be reflected in Ketcher until a proper (re-)integration is made. We'll keep this issue in our backlog, but please do not expect an immediate solution 😞

**Comment by NataliaDSmirnova** [comment]
To be closed as seemed being answered.
