### ISSUE TITLE
Configure Codeclimate

### ISSUE THREAD

**Issue by r1z3rISGOD** [epam/miew#384]
Sometimes codeclimate warn on files that should not be checked. It means, we need to try to configure it.

**Comment by r1z3rISGOD** [comment]
To exclude files from the list of validated files, we need to edit the .codeclimate.yml file. Beforehand, it is necessary to analyze all issues, and therefore, work on the task is temporarily postponed.

**Comment by NataliaDSmirnova** [comment]
It is an outdated task as we made a jump into another branch with another folder structure.
The task is rejected.
