### ISSUE TITLE
Fix miew-app

### ISSUE THREAD

**Issue by AnaMoskvina** [epam/miew#394]
Miew-app crashes

Steps to reproduce:
- start miew-app
- chose any structure from the gallery
- click the menu button

**Comment by AnaMoskvina** [comment]
Same behavior appeared before (in release 0.0.9),
Other issues in miew-app (comparing to demo):
- representation menu is missing;
- render settings are not implemented (just mark-up boilerplate);

**Comment by paulsmirnov** [comment]
Closing as irrelevant / out of scope for the `main` branch. We'll get back to it if needed.
