### ISSUE TITLE
Fix miew canvas squashing

### ISSUE THREAD

**Issue by AnaMoskvina** [epam/miew#412]
Issue in miew package.
Sometimes (in about 10% cases) .miew-canvas div does not occupy 100% of container's height and it's height is just 22px.
This issue can be fixed by workaround with explicitly setting 100% height in parent component (as it's done in miew-react).
Need to figure out, what causes such behavior (and in what cases), and fix the problem in miew package (after workaround can be removed from miew-react and from example with transparent background).

**Comment by paulsmirnov** [comment]
Actually, it works as expected as 100% means the full height of its parent. The parent owns its height.

"In order for a percentage value to work for height, the parent's height must be determined. The only exception is the root element <html>, which can be a percentage height. " (https://stackoverflow.com/a/7049918/1852238)

We could try the "modern approach" with the height relative to the viewport, but I wouldn't rush doing so and come up with precise requirements for this _feature_ first. 100% of the viewport is not what we want for an embedded viewer.
