### ISSUE TITLE
Can't make the examples to work

### ISSUE THREAD

**Issue by popstatic** [epam/miew#414]
I clone the repoo and then no intstructions are available tu make it work...

Any idea to help me ?
many thanks !

**Comment by AnaMoskvina** [comment]
Dear @popstatic,

Thank you for your interest in Miew.
May be, you can find some helpful information in [the reedme file](https://github.com/epam/miew#readme)
To learn about an extensive API description, please, check out miew/documentation/index.html at your machine
If you want to run the demo application, please, install dependencies with 'yarn install' in the project folder, and run 'yarn serve' command

Feel free to ask, if you have any questions, we will be happy to help.

Best regards,
Miew team

**Comment by paulsmirnov** [comment]
This issue was closed because it has been inactive for a few months. Hopefully, it means that the reply was accepted :)
