### ISSUE TITLE
Change modes and colors

### ISSUE THREAD

**Issue by nasirzid** [epam/miew#419]
How can I change display mode and color? in react

**Comment by newmys** [comment]
`
// set the current visual, if use multiFile opts
miew.setCurrentVisual(visualName)
// set the rep which you want to change
miew.rep(index, { color, mode, selector, material })
`

**Comment by nasirzid** [comment]
My files were in .mol format when I convert them into .pbd format it is automatically showing Balls display mode. I think files contains display properties as well.
