### ISSUE TITLE
How to select secondary structures in gui's terminal

### ISSUE THREAD

**Issue by ChemBioScripting** [epam/miew#432]
Hello, I'm learning how to use the Miew's API. I'm using the terminal inside the [demo](https://miew.opensource.epam.com/)  to test some commands but, reading [here](https://lifescience.opensource.epam.com/miew/selectors.html), I'm not able to selectively select secondary structures (like helices, sheets, coils, etc.) to apply a custom color to them for example.

Another question is about `miew.view()` and `miew.getURL()`, which in the terminal seem to correspond respectively to `view` and `url`, but I'm not achieving how to pass parameters like `opts.view`, for `miew.getURL()`, in the gui's terminal, to extend default `url` output, thank you.

**Comment by ChemBioScripting** [comment]
I see that the default color palettes (`CPK`, `Jmol`, `VMD`) are defined in [these files](https://github.com/epam/miew/blob/master/packages/miew/src/gfx/palettes/) with `palette.secondaryColors`. Has the possibility of setting them via Miew's API from built-in terminal been implemented?

**Comment by paulsmirnov** [comment]
Hello! The built-in terminal commands are for end-users while the API is for developers, so they do not necessarily match each other. I think `url -v` in the terminal solves your question but it is not always the case. You can get help on this particular command by typing `help url`, and it will tell you about the `-v` switch.

As for selecting secondary structures, I'm afraid there is no such selector in the selection language: https://github.com/epam/miew/blob/master/packages/miew/src/utils/SelectionParser.jison#L19
You can select any range of residues with `sequence 32:35` as in the following example: https://miew.app/?l=pdb:1CRN&p=macro&r=1&s=sequence+32:35&m=VW&c=UN!color:0xFF0000

**Comment by paulsmirnov** [comment]
You can switch to a different palette from a terminal using `set palette VM` command (to use VMD-like colors) but not change the colors of a predefined palette. If you use Miew API however, you can create your own palette and add it to the list of palettes. I cannot verify it right now but I think it should be something like `Miew.palettes.register(...)`

**Comment by ChemBioScripting** [comment]
> You can switch to a different palette from a terminal using `set palette VM` command (to use VMD-like colors) but not change the colors of a predefined palette. If you use Miew API however, you can create your own palette and add it to the list of palettes. I cannot verify it right now but I think it should be something like `Miew.palettes.register(...)`

Thank you so much, @paulsmirnov, for all the pointers! Taking a closer look at the GUI, I noticed the possibility of making selections that can be customized as a graphical representation, a task made easy by the possibility of selecting the residues in the scene by identifying the number of the selection, excellent!

It remains useful to add the ability to create custom color palettes for the secondary structures (like the possibility to also add a custom uniform color for the selection in the cartoon mode). It could be placed in the same section that allows you to select CPK, Jmol or VMD, similarly to what is already possible in Representations. If the API already provides the ability to add custom palettes for pre-designed entries, it's even easier!

Great project! Thank you

**Comment by ChemBioScripting** [comment]
> 

`url -v -s` solved the other question, thank you @paulsmirnov !

**Comment by NataliaDSmirnova** [comment]
Close as seemed being answered
