### ISSUE TITLE
Migrate lib building from rollup to webpack

### ISSUE THREAD

**Issue by NataliaDSmirnova** [epam/miew#436]
`root/packages/lib` already contains a `webpack.config.js` for demo building.

We should add the building of the `lib` in the config file.

**Comment by paulsmirnov** [comment]
Do not forget the last chance to reconsider the migration 😁😁😁 as part of this task.

> _Rollup and Webpack are both JavaScript bundlers, but they have different strengths and weaknesses. Rollup is faster and more efficient, but it has a smaller feature set._ (c) ChatGPT4

💡 See also [npm trends](https://npmtrends.com/esbuild-vs-rollup-vs-webpack) on a chart.
Webpack usage is decreasing for some reason + something new and fast-growing has appeared (esbuild). Not that I ask you to change the build system... Let it be a knowledge-sharing session for all of us 😉
