### ISSUE TITLE
Remove dist/ contents from git

### ISSUE THREAD

**Issue by NataliaDSmirnova** [epam/miew#439]
**Is your feature request related to a problem? Please describe.**
We commit dist/ only for new release

**Describe the solution you'd like**

- Find in rep history the moment when they were added, and verify the reason to do that
- Add dist/ content to gitignore

**Comment by DmitryLukyanov** [comment]
Can you please elaborate the goal here? As I understand, the `dist` folder was under the git at least all the time when the sources are in github (6+ years). Initially, it was placed in the root folder, then [here](https://github.com/epam/miew/commit/389690b5db38dd5f0cf8a3034e0a2cf6460a7727), it was moved into `packages/lib`.

**Comment by NataliaDSmirnova** [comment]
the ticket isn't actual
