### ISSUE TITLE
Bump eslint version to 8.50 (+ plugins)

### ISSUE THREAD

**Issue by NataliaDSmirnova** [epam/miew#441]
**Is your feature request related to a problem? Please describe.**
Some of the plugins have changed its major. It's time to use actual eslint.

- use `yarn upgrade-interactive` command for a useful interface of package versions

**Comment by paulsmirnov** [comment]
@NataliaDSmirnova - 1) do you understand why this task is not closed yet? It is marked as "fixed by 443" but is still open; 2) given that we changed to a different branch ("main") do we need to do this again?
