### ISSUE TITLE
webpack build with npm Miew version broken

### ISSUE THREAD

**Issue by Jo-Zh** [epam/miew#448]
Hi!
is this npm module https://www.npmjs.com/package/miew still valid? I am using webpack to build and ran into the following issues:
**Describe the bug**
1. undefined version
2. Uncaught TypeError: **e** is not a constructor
    at window.onload (bundle.js:2:1286181)
   `
    window.onload = function() {
        var t = new **e**({
            container: document.getElementsByClassName("miew-container")[0],
            load: "1CRN"
        });
  `

**To Reproduce**
1. Installed npm i miew, 
2. and followed these steps for webpack user: https://lifescience.opensource.epam.com/miew/embed.html
 index.html 
` 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Miew via Webpack</title>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.min.js"></script>
  
   <script src="./dist/bundle.js"></script>
</head>
<body>
  <div class="miew-container" style="width:640px; height:480px"></div>
</body>
</html>
`

index.js
`
// require('Miew.min.css');  This is not found in node module

var Miew = require('miew');

window.onload = function() {
  var viewer = new Miew({
    container: document.getElementsByClassName('miew-container')[0],
    load: '1CRN',
  });

  if (viewer.init()) {
    viewer.run();
  }
};

`
webpack.config.js

`
module.exports = {
  entry: './index.js',
  output: {
    filename: 'bundle.js'
  },
  module: {
    rules: [{
      test: /\.css$/,
      use: ['style-loader', 'css-loader'],
    }],
  },
};

`
3. npm run build

**Expected behavior**
showing 3D view.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser: chrome
 - Version 115.0.5790.102 

Thank you!

**Comment by NataliaDSmirnova** [comment]
Hi @Jo-Zh!

Thank you for paying attention to the problem. I confirm, there is a problem with the documentation.
Please give us some time for investigation. We'll return soon.

BTW, Miew package is valid, the problem is with the example.

**Comment by Jo-Zh** [comment]
Thanks Natalia, 
just added .default after require('miew') like this:
var Miew = require('miew')**.default**
There is no error anymore, seems worked. **But just showing a plain black rectangle block. Nothing inside?** 
And in the console, 
1. The Miew.VERSION still undefined.
2. got list of violations:
`
bundle.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
fb @ bundle.js:2
value @ bundle.js:2
window.onload @ bundle.js:2
bundle.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
fb @ bundle.js:2
value @ bundle.js:2
window.onload @ bundle.js:2
bundle.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
fb @ bundle.js:2
value @ bundle.js:2
window.onload @ bundle.js:2
bundle.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
db @ bundle.js:2
value @ bundle.js:2
window.onload @ bundle.js:2
bundle.js:2 [Violation] 'requestAnimationFrame' handler took 55ms
bundle.js:2 fetch: 2756.19091796875 ms
bundle.js:2 [Violation] 'setTimeout' handler took 161ms
bundle.js:2 parse: 162.030029296875 ms
bundle.js:2 build: 42.358154296875 ms

`

**Comment by Jo-Zh** [comment]
Great, it works now, Thank you! :+1:
