### ISSUE TITLE
Update embed.md and uploaded documentation for examples

### ISSUE THREAD

**Issue by NataliaDSmirnova** [epam/miew#449]
Tutorial [`embed.md`](https://github.com/epam/miew/blob/main/packages/lib/docs/tutorials/embed.md) is outdated. The instructions for at least Webpack doesn't work.

* Check instructions in other sections of the tutorial
* Update outdated (see https://github.com/epam/miew/issues/448#issuecomment-1669956050 for working Webpack instruction for Node.js v14)
* Upload fixed docs to https://lifescience.opensource.epam.com/miew/embed.html

**Comment by paulsmirnov** [comment]
Was unintentionally closed by the PR. Reopening until lifescience docs are also fixed.
