### ISSUE TITLE
Remove lerna, update yarn

### ISSUE THREAD

**Issue by NataliaDSmirnova** [epam/miew#453]
- Remove lerna
- Use yarn instead to support monorepo
- Also fix appveyor 

As an example of a similar update PR https://github.com/epam/miew/pull/343
https://github.com/epam/miew/pull/354

**Comment by paulsmirnov** [comment]
Why not to remove Travis in a separate PR? It is a standalone small task that gives an immediate result 😉

**Comment by NataliaDSmirnova** [comment]
> Why not to remove Travis in a separate PR? It is a standalone small task that gives an immediate result 😉 I mean, maybe it is too much unrelated in one task...

You're right. I've removed Travis mention from the description.
