### ISSUE TITLE
Miew will disabled s/+/- keys on pages where it's initialized

### ISSUE THREAD

**Issue by themoenen** [epam/miew#534]
**Describe the bug**
The `s` key as well as the numeric keyboard's `+` / `-` keys are disabled when you try to type on a page where Miew is initialized.

**To Reproduce**
- Initiate Miew with default settings
- Try typing in an input field on the same page as the Miew viewer

**Expected behavior**
`s` key should type 's' character.

**Additional context**
Responsible code:
```
Miew.prototype._onKeyDown = function (event) {
    [...]
    switch (event.keyCode) {
    case 'S'.charCodeAt(0):
        event.preventDefault();
        event.stopPropagation();
        settings.set('ao', !settings.now.ao);
        this._needRender = true;
        break;
    [...]
}
```

In the change log there's a mention of when and why this was implemented:

```
## [0.7.4] - 2017-10-16
- Prevent 's' key from appearing in the terminal when it is closed.
```

**Comment by paulsmirnov** [comment]
Thank you. As we discussed previously in #524, eating keypresses is indeed a bold behavior for the library. However, does this particular description of the issue make it a bug? I mean, why not just switch it off on your page with `miew.enableHotKeys(false)` that exists specifically for the case you described? The demo application at https://miew.app/ perfectly allows typing all characters into the integrated terminal 🙂

Please give us some time to review the PR. Thanks again!
