### ISSUE TITLE
Cannot load an MMTF file

### ISSUE THREAD

**Issue by paulsmirnov** [epam/miew#539]
**Describe the bug**
Miew cannot load MMTF files using PDBID now. Perhaps, the data source stopped working (mmtf.rcsb.org).

**To Reproduce**
1. Go to 'https://miew.app'
2. Open Menu -> Gallery -> 4TNW
4. See error. Check the browser console for details:

```
GET https://mmtf.rcsb.org/v1.0/full/4TNW net::ERR_NAME_NOT_RESOLVED
```

You can also visit https://miew.app/examples/api.html and click on "Load 4XN6.mmtf"

**Expected behavior**
The molecules from the Gallery should load. The syntax "mmtf:4XN6" should also work in the Load menu.

**Comment by paulsmirnov** [comment]
January 15, 2024:

> _As of July 2, 2024, RCSB PDB will no longer serve PDB data in the MMTF compression format. Users are strongly encouraged to switch to accessing the data files offered in the [compressed BinaryCIF (BCIF) format.](https://www.rcsb.org/docs/programmatic-access/file-download-services#pdb-entry-files)_

Ref: https://www.rcsb.org/news/feature/65a1af31c76ca3abcc925d0c

**Comment by paulsmirnov** [comment]
I guess what we can do now is:
- change the Gallery and examples to use PDB or CIF instead of MMTF,
- remove the "mmtf:" prefix support from the load function,
- keep the MMTF file format support for backward compatibility,
- consider implementing the BCIF file format and prefix in the future.

@NataliaDSmirnova?

**Comment by NataliaDSmirnova** [comment]
I agree. The approach you've suggested seems the best for me.
