### ISSUE TITLE
Zoom will get lost in space

### ISSUE THREAD

**Issue by themoenen** [epam/miew#556]
**Describe the bug**
When you zoom out past a certain point where the molecule is no longer visible, you will no longer be able to zoom back in and effectively "lost" your molecule.

This problem is exacerbated by the fact that zoom is connected to the mousewheel, making it more likely to happen when you try to scroll down a page but instead zoom out by accident.

It would make sense to limit both zoom in and out.

**To Reproduce**
1. Use mousewheel to zoom out by scrolling down, until the molecule disappears. Continue screolling down a bit.
2. Scroll up to zoom in

**Expected behavior**
Molecule should reappear.

**Actual behavior**
Molecule does not reappear.

**Screenshots**
n/a

**Desktop (please complete the following information):**
Not relevant but:
 - OS: macOS Sonoma 14.4.1 (23E224)
 - Browser: Chrome
 - Version: 128.0.6613.113 (Official Build) (arm64)

**Additional context**
n/a

**Comment by NataliaDSmirnova** [comment]
@themoenen thank you for reporting.

We understand that molecules may occasionally disappear when zooming out significantly. This is a known behavior that can be reversed by zooming back in. So we cannot reproduce it as a bug.

We agree that this can be frustrating in certain situations. We've prioritized addressing this issue in our roadmap but are exploring alternative solutions to the approach suggested in #558.

We don't recognize it as a bug. Let's continue to discuss it in #557.
